// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tictactoe_test/features/game/domain/entities/difficulty.dart';
import 'package:tictactoe_test/features/game/domain/entities/game_mode.dart';
import 'package:tictactoe_test/features/score_history/data/models/score_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DifficultyAdapter());
    registerAdapter(GameModeAdapter());
    registerAdapter(ScoreModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DifficultyAdapter());
    registerAdapter(GameModeAdapter());
    registerAdapter(ScoreModelAdapter());
  }
}
